services:
  # mysql:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpass
  #     MYSQL_DATABASE: transcriptions
  #     MYSQL_USER: app
  #     MYSQL_PASSWORD: apppass
  #   ports: ["3306:3306"]
  #   command:
  #     [
  #       "--character-set-server=utf8mb4",
  #       "--collation-server=utf8mb4_unicode_ci",
  #     ]
  #   volumes: ["mysql_data:/var/lib/mysql"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api # <— builds the api target
    environment:
      # DATABASE_URL: mysql+mysqlconnector://app:apppass@mysql:3306/transcriptions?ssl_mode=DISABLED
      DATABASE_URL: sqlite:////data/app.db
      REDIS_URL: redis://redis:6379/0
      APP_NAME: whisperx-transcription
      API_PREFIX: /v1
    ports: ["8080:8080"]
    depends_on:
      # - mysql
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker # <— builds the worker target
    environment:
      # DATABASE_URL: mysql+mysqlconnector://app:apppass@mysql:3306/transcriptions?ssl_mode=DISABLED
      DATABASE_URL: sqlite:////data/app.db
      REDIS_URL: redis://redis:6379/0
      WHISPERX_DEVICE: cpu
      WHISPERX_COMPUTE_TYPE: int8
      WHISPERX_MODEL_NAME: small
      WHISPERX_ENABLE_ALIGNMENT: "true"
      WHISPERX_ENABLE_DIARIZATION: "false"
    depends_on:
      # - mysql
      - redis
# volumes:
# mysql_data:
