"""create transcription_jobs

Revision ID: 9bb8f8954bcb
Revises: 
Create Date: 2025-07-31 13:58:02.501634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '9bb8f8954bcb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transcription_jobs_status', table_name='transcription_jobs')
    op.drop_table('transcription_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcription_jobs',
    sa.Column('job_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('audio_url', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('enqueued_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('request_metadata', sqlite.JSON(), nullable=True),
    sa.Column('language', sa.VARCHAR(length=16), nullable=True),
    sa.Column('duration_sec', sa.FLOAT(), nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('device', sa.VARCHAR(length=16), nullable=True),
    sa.Column('compute_type', sa.VARCHAR(length=32), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('transcript_json', sqlite.JSON(), nullable=True),
    sa.Column('result_blob_url', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('ix_transcription_jobs_status', 'transcription_jobs', ['status'], unique=False)
    # ### end Alembic commands ###
